name: Build and Release DMG

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 Pillow pyinstaller
        brew install ffmpeg
    - name: Install test dependencies
      run: |
        pip install pytest pytest-cov
    - name: Install package in editable mode
      run: pip install -e .
    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
    - name: Build app with PyInstaller
      run: |
        pyinstaller --windowed --icon file_manager_icon.icns mac_file_manager_pro/file_manager.py
    - name: Create DMG
      run: |
        mkdir -p dist-dmg
        cp -R dist/file_manager.app dist-dmg/
        ln -s /Applications dist-dmg/Applications
        hdiutil create -volname "MAC File Manager Pro" -srcfolder dist-dmg -ov -format UDZO MAC_File_Manager_Pro.dmg
    - name: Upload DMG to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: MAC_File_Manager_Pro.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
