name: Build and Release DMG
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 Pillow pyinstaller pytest pytest-cov
        brew install ffmpeg
    - name: Install package in editable mode
      run: pip install -e .
    - name: Debug files and packages
      run: |
        pwd
        ls -la
        ls -la mac_file_manager_pro/
        pip list
    - name: Run tests with coverage
      run: pytest --cov=. --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
    - name: Clean build directories
      run: rm -rf dist build
    - name: Build app with PyInstaller
      run: pyinstaller --windowed --icon file_manager_icon.icns mac_file_manager_pro/file_manager.py
    - name: Create DMG
      run: |
        mkdir -p dist-dmg
        cp -R dist/file_manager.app dist-dmg/
        ln -s /Applications dist-dmg/Applications
        hdiutil create -volname "FileManager" -srcfolder dist-dmg -ov -format UDZO app.dmg
    - name: Upload DMG to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: app.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
